apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "bdc-ingest.fullname" . }}
  labels:
    {{- include "bdc-ingest.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bdc-ingest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bdc-ingest.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.jobExecutor.image.repository }}
          imagePullPolicy: {{ .Values.jobExecutor.image.pullPolicy | default "Always" }}
          resources:
            {{- toYaml .Values.jobExecutor.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: {{ .Values.jobExecutor.restartPolicy | default "Never" }}
          command:
            -
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
