# Default values for bdc-ingest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Amount of storage needed to download all BDC data.
dataStorage: 200Mi

# LakeFS information.
lakeFS:
  host: https://lakefs.apps.renci.org/api/v1
  username: TODO # see in values-secret.yaml
  password: TODO # see in values-secret.yaml

# Settings for the Job executor pod.
jobExecutor:
  image:
    repository: containers.renci.org/helxplatform/dug-data-ingest
    tag: add-heal-platform-mds
    pullPolicy: Always
  restartPolicy: Never
  backoffLimit: 0
  resources:
    limits:
      cpu: 1000m
      memory: 1G
    requests:
      cpu: 500m
      memory: 1G
  securityContext: {}
  podAnnotations: {}
  podLabels: {}
  nodeSelector: {}
  affinity: {}
  tolerations: {}
