# Default values for bdc-ingest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Amount of storage needed to download all BDC data.
dataStorage: 200Mi

# LakeFS information.
lakeFS:
  host: https://lakefs.apps.renci.org/api/v1
  username: TODO # see in values-secret.yaml
  password: TODO # see in values-secret.yaml
  repository: bdc-test

# Settings for the Job executor pod.
jobExecutor:
  image:
    repository: ghcr.io/helxplatform/dug-data-ingest
    tag: add-bdc-ingest # TODO: change to `latest` once properly published.
    pullPolicy: Always
  restartPolicy: Never
  resources:
    limits:
      cpu: 1000m
      memory: 1G
    requests:
      cpu: 500m
      memory: 1G
